---
title: "p8105_hw3_tk2886"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(patchwork)
library(p8105.datasets)

## Set Global Options 
knitr::opts_chunk$set(
  fig.wwidth = 6,
  fig.asp = .6, 
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

Loading Data and Cleaning Data with janitor
```{r}
data("instacart")

instacart_df = 
  instacart %>% 
  janitor::clean_names()
```

Analysis of instacart data
```{r}
dimension_instacart = dim(instacart_df)
dimension_instacart
instacart_row = nrow(instacart_df)
instacart_row
instacart_col = ncol(instacart_df)
instacart_col
key_variables = names(instacart_df)
key_variables
```
The dimension of the instacart dataframe is `r dimension_instacart`. The dimensions represents the number of rows and the columns. The number of rows in the instacart dataframe are `r instacart_row`. The number of columns in the instacart dataframe are `r instacart_col`. 


